env:
    browser: true
    es2021: true
extends:
    - eslint:recommended
    - plugin:@typescript-eslint/recommended
parser: '@typescript-eslint/parser'
parserOptions:
    ecmaVersion: 13
    sourceType: module
plugins:
    - '@typescript-eslint'
rules:
    "@typescript-eslint/ban-types": off
    "@typescript-eslint/no-empty-function": off
    "@typescript-eslint/no-unused-vars": off
    require-jsdoc:
        - warn
        -   require:
                FunctionDeclaration: true
                MethodDefinition: true
                ClassDeclaration: true
                ArrowFunctionExpression: true
                FunctionExpression: true
    valid-jsdoc:
        - warn
        -   prefer:
                return: returns
            requireParamType: false
            requireReturnType: false
            requireReturn: false
    no-prototype-builtins: off
    indent:
        - error
        - 4
        -   SwitchCase: 1
    linebreak-style:
        - error
        - windows
    quotes:
        - error
        - single
    semi:
        - error
        - always